-- Create a test user with known credentials for debugging
-- First, let's try to manually insert a test user with proper password hash

-- Generate a test user with email test@example.com and password Mis@478992
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_sent_at,
  email_change,
  email_change_token_new,
  email_change_token_current,
  phone_change_sent_at,
  phone_change,
  phone_change_token,
  reauthentication_sent_at,
  reauthentication_token,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change_token_new,
  phone_change_token_current,
  email_change_confirm_status,
  banned_until,
  delete_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'test@example.com',
  crypt('Mis@478992', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  null,
  '',
  '',
  '',
  null,
  '',
  '',
  null,
  '',
  '{"provider": "email", "providers": ["email"]}',
  '{"full_name": "Test User", "trader_name": "TestTrader"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  0,
  null,
  null
) ON CONFLICT (email) DO NOTHING;