// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxrgknvprkvtdpzmpclh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cmdrbnZwcmt2dGRwem1wY2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTczMjQsImV4cCI6MjA2OTc3MzMyNH0.CxqJVEg1z6GYJeWqzcU_Ab1uV0Kvbg-CzzkDLJSwOiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});